[build-system]
build-backend = "hatchling.build"
requires = [
    "hatchling",
]

[project]
name = "demolizzen"
description = "Eve Online Discord Bot."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Geuthur", email = "devgeuthur@gmail.com" },
]
requires-python = ">=3.10"
classifiers = [
    "Environment :: Console",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
dynamic = [
    "version",
]
dependencies = [
    "django==5.2.8",
    "mysqlclient==2.2.7",
    "oauthlib==3.3.1",
    "pillow==12",
    "pre-commit==4.3",
    "py-cord==2.7.0rc2",
    "pycolorise==1",
    "python-dotenv==1.2.1",
    "python-jose==3.5",
    "pytz==2025.2",
    "requests==2.32.5",
    "requests-oauthlib==2",
    "typing-extensions==4.15",
    "yarl==1.22",
]
optional-dependencies.tests-demolizzen-latest = [
    "coverage",
]
urls.Changelog = "https://github.com/Geuthur/Demolizzen/blob/master/CHANGELOG.md"
urls.Documentation = "https://github.com/Geuthur/Demolizzen/blob/master/README.md"
urls.Donations = "https://ko-fi.com/Geuthur"
urls.Homepage = "https://github.com/Geuthur/Demolizzen"
urls.Source = "https://github.com/Geuthur/Demolizzen"
urls.Tracker = "https://github.com/Geuthur/Demolizzen/issues"

[tool.hatch.build]
include = [
    "demolizzen/",
]

[tool.hatch.version]
path = "demolizzen/__init__.py"
