[tox]
requires =
    tox>=4.2
env_list =
    demolizzen-{latest}
    py{313, 312, 311, 310}
no_package = true
usedevelop = true

[testenv]
deps =
    coverage
commands =
    coverage run runtests.py demolizzen -v 2
    coverage report -m
    coverage xml

[testenv:demolizzen-latest]
set_env =
    DJANGO_SETTINGS_MODULE = testenv.settings
install_command =
    python -m pip install -e ".[tests-demolizzen-latest]" -U {opts} {packages}
