# Generated by Django 5.2.6 on 2025-09-10 12:15

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EconomyShip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "ship_type",
                    models.CharField(
                        choices=[
                            ("frigate", "Frigate"),
                            ("destroyer", "Destroyer"),
                            ("cruiser", "Cruiser"),
                            ("battlecruiser", "Battlecruiser"),
                            ("battleship", "Battleship"),
                            ("carrier", "Carrier"),
                            ("dreadnought", "Dreadnought"),
                            ("super_carrier", "Super Carrier"),
                            ("mining_barge", "Mining Barge"),
                            ("exhumer", "Exhumer"),
                            ("industrial", "Industrial"),
                            ("rorqual", "Rorqual"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                ("ship_speed", models.IntegerField()),
                ("payout_bonus", models.IntegerField(default=0)),
                ("success_bonus", models.IntegerField(default=0)),
                ("price", models.BigIntegerField()),
                ("insurance", models.BigIntegerField()),
                ("description", models.TextField()),
                ("active", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mining", "Mining"),
                            ("raiding", "Raiding"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "economy_ship",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="EconomyShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.BigIntegerField()),
                ("description", models.TextField()),
                (
                    "shop_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("trophies", "Trophies"),
                            ("skins", "Skins"),
                            ("furniture", "Furniture"),
                            ("drinks", "Drinks"),
                            ("food", "Food"),
                            ("misc", "Miscellaneous"),
                            ("openable", "Openable"),
                            ("boosters", "Boosters"),
                            ("special", "Special"),
                            ("unique", "Unique"),
                            ("super_rare", "Super Rare"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "economy_shop",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="EconomySolarSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("security_status", models.FloatField()),
                ("description", models.TextField()),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "economy_solar_system",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="EveEntityCache",
            fields=[
                ("entity_id", models.IntegerField(primary_key=True, serialize=False)),
                ("entity_name", models.CharField(max_length=64)),
                ("category", models.CharField(max_length=64)),
                ("created", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "eve_entity_cache",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="EvePricecache",
            fields=[
                (
                    "item_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("price", models.BigIntegerField()),
                ("buy", models.BigIntegerField()),
                (
                    "tradehub",
                    models.CharField(
                        choices=[
                            ("Jita IV - Moon 4 - Caldari Navy Assembly Plant", "Jita"),
                            ("Amarr VIII (Oris) - Emperor Family Academy", "Amarr"),
                            ("Rens VI - Moon 8 - Brutor Tribe Treasury", "Rens"),
                            (
                                "Dodixie IX - Moon 20 - Federation Navy Assembly Plant",
                                "Dodixie",
                            ),
                            ("Hek VIII - Moon 12 - Boundless Creation Factory", "Hek"),
                            ("Alliance Tournament", "Alliance Tournament"),
                        ],
                        max_length=255,
                    ),
                ),
                ("expiration", models.DateTimeField()),
            ],
            options={
                "db_table": "eve_price_cache",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GuildProfile",
            fields=[
                ("guild_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("guild_name", models.CharField(max_length=255)),
                ("main_channel", models.TextField(null=True)),
                ("mention", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "guild_profile",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="InvTypes",
            fields=[
                ("typeID", models.IntegerField(primary_key=True, serialize=False)),
                ("groupID", models.IntegerField(null=True)),
                ("typeName", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(null=True)),
                ("mass", models.FloatField(null=True)),
                ("volume", models.FloatField(null=True)),
                ("capacity", models.FloatField(null=True)),
                ("portionSize", models.IntegerField(null=True)),
                ("raceID", models.IntegerField(null=True)),
                (
                    "BaseModelPrice",
                    models.DecimalField(decimal_places=4, max_digits=19, null=True),
                ),
                ("published", models.BooleanField(null=True)),
                ("marketGroupID", models.IntegerField(null=True)),
                ("iconID", models.IntegerField(null=True)),
                ("soundID", models.IntegerField(null=True)),
                ("graphicID", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "invTypes",
                "default_permissions": (),
                "indexes": [
                    models.Index(fields=["groupID"], name="ix_invTypes_groupID")
                ],
            },
        ),
        migrations.CreateModel(
            name="MapSolarSystems",
            fields=[
                ("regionID", models.IntegerField(null=True)),
                ("constellationID", models.IntegerField(null=True)),
                (
                    "solarSystemID",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("solarSystemName", models.CharField(max_length=100, null=True)),
                ("x", models.FloatField(null=True)),
                ("y", models.FloatField(null=True)),
                ("z", models.FloatField(null=True)),
                ("xMin", models.FloatField(null=True)),
                ("xMax", models.FloatField(null=True)),
                ("yMin", models.FloatField(null=True)),
                ("yMax", models.FloatField(null=True)),
                ("zMin", models.FloatField(null=True)),
                ("zMax", models.FloatField(null=True)),
                ("luminosity", models.FloatField(null=True)),
                ("border", models.BooleanField(null=True)),
                ("fringe", models.BooleanField(null=True)),
                ("corridor", models.BooleanField(null=True)),
                ("hub", models.BooleanField(null=True)),
                ("international", models.BooleanField(null=True)),
                ("regional", models.BooleanField(null=True)),
                ("constellation", models.BooleanField(null=True)),
                ("security", models.FloatField(null=True)),
                ("factionID", models.IntegerField(null=True)),
                ("radius", models.FloatField(null=True)),
                ("sunTypeID", models.IntegerField(null=True)),
                ("securityClass", models.CharField(max_length=2, null=True)),
            ],
            options={
                "db_table": "mapSolarSystems",
                "default_permissions": (),
                "indexes": [
                    models.Index(fields=["regionID"], name="ix_mapSyst_regID"),
                    models.Index(fields=["constellationID"], name="ix_mapSyst_constID"),
                    models.Index(fields=["solarSystemID"], name="ix_mapSyst_solID"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                ("user_name", models.CharField(max_length=255)),
                ("experience", models.BigIntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_guild",
                        to="demolizzen.guildprofile",
                    ),
                ),
            ],
            options={
                "db_table": "user_profile",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="UserMiningMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cooldown", models.DateTimeField(null=True)),
                ("chance", models.IntegerField(null=True)),
                ("salary", models.IntegerField(null=True)),
                ("active", models.BooleanField(default=False)),
                ("ship_type", models.CharField(default="normal", max_length=50)),
                ("insurance", models.IntegerField(default=0)),
                (
                    "ship",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mining_ships",
                        to="demolizzen.economyship",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mining_mission",
                        to="demolizzen.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "user_mining_mission",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="UserDailyReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_claim", models.DateTimeField(null=True)),
                ("streak", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reward",
                        to="demolizzen.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "user_reward",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="UserBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet", models.BigIntegerField(default=0)),
                ("bank", models.BigIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account",
                        to="demolizzen.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "user_bank",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="UserBag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bags",
                        to="demolizzen.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "user_bag",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="UserRaidMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cooldown", models.DateTimeField(null=True)),
                ("chance", models.IntegerField(null=True)),
                ("salary", models.IntegerField(null=True)),
                ("active", models.BooleanField(default=False)),
                ("ship_type", models.CharField(default="normal", max_length=50)),
                ("insurance", models.IntegerField(default=0)),
                (
                    "ship",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raiding_ships",
                        to="demolizzen.economyship",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raid_mission",
                        to="demolizzen.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "user_raid_mission",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("background", models.TextField()),
                ("xp_colour", models.TextField()),
                ("blur", models.IntegerField()),
                ("border", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="demolizzen.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "user_settings",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="UserWorkMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cooldown", models.DateTimeField(null=True)),
                (
                    "job",
                    models.CharField(
                        choices=[
                            ("Unemployed", "Unemployed"),
                            ("Miner", "Miner"),
                            ("Hauler", "Hauler"),
                            ("Explorer", "Explorer"),
                            ("Trader", "Trader"),
                            ("Bounty Hunter", "Bounty Hunter"),
                            ("Pirate", "Pirate"),
                            ("Smuggler", "Smuggler"),
                            ("Mission Runner", "Mission Runner"),
                            ("Industrialist", "Industrialist"),
                            ("Corporate Agent", "Corporate Agent"),
                            ("Fleet Commander", "Fleet Commander"),
                            ("Warlord", "Warlord"),
                            ("Dreadnought", "Dreadnought"),
                        ],
                        default="Unemployed",
                        max_length=100,
                    ),
                ),
                ("job_duration", models.IntegerField(default=3600)),
                ("salary", models.IntegerField(null=True)),
                ("experience", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("chance", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_mission",
                        to="demolizzen.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "user_work_mission",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ZKillboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.BigIntegerField()),
                ("group_id", models.BigIntegerField(null=True)),
                ("losses", models.BooleanField(default=False)),
                ("threshold", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demolizzen.guildprofile",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demolizzen.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "zKillboard",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="UserBagItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("item_type", models.CharField(max_length=50)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "user_bag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="demolizzen.userbag",
                    ),
                ),
            ],
            options={
                "db_table": "user_bag_items",
                "default_permissions": (),
                "unique_together": {("user_bag", "item_name")},
            },
        ),
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.BigIntegerField()),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("has_token_error", models.BooleanField(default=False)),
                ("error_message", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demolizzen.guildprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demolizzen.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "access_tokens",
                "default_permissions": (),
                "unique_together": {("user", "guild")},
            },
        ),
    ]
