# Generated by Django 5.2.6 on 2025-09-10 18:37

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demolizzen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuildSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("bank_interest", models.FloatField(default=0.001)),
                ("custom_commands", models.JSONField(null=True)),
                ("disabled_commands", models.JSONField(null=True)),
                ("disabled_cogs", models.JSONField(null=True)),
                ("enabled_cogs", models.JSONField(null=True)),
                (
                    "guild",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="demolizzen.guildprofile",
                    ),
                ),
            ],
            options={
                "db_table": "guild_settings",
                "default_permissions": (),
            },
        ),
    ]
