# Generated by Django 5.2.6 on 2025-09-12 20:40

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demolizzen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuildSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("bank_interest", models.FloatField(default=0.001)),
                (
                    "custom_commands",
                    models.JSONField(
                        help_text="Custom commands for the guild", null=True
                    ),
                ),
                (
                    "disabled_commands",
                    models.JSONField(
                        help_text="Disabled commands for the guild", null=True
                    ),
                ),
                (
                    "disabled_cogs",
                    models.JSONField(
                        help_text="Disabled cogs for the guild", null=True
                    ),
                ),
                (
                    "enabled_cogs",
                    models.JSONField(help_text="Enabled cogs for the guild", null=True),
                ),
                (
                    "guild",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guild_settings",
                        to="demolizzen.guildprofile",
                    ),
                ),
            ],
            options={
                "db_table": "guild_settings",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GuildTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.PositiveIntegerField(help_text="Ticket number"),
                ),
                (
                    "channel_id",
                    models.BigIntegerField(help_text="ID of the ticket channel"),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        help_text="ID of the user who created the ticket"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_by", models.BigIntegerField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("claimed_by", models.BigIntegerField(blank=True, null=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guild_tickets",
                        to="demolizzen.guildprofile",
                    ),
                ),
            ],
            options={
                "db_table": "guild_tickets",
                "default_permissions": (),
                "unique_together": {("guild", "ticket_number")},
            },
        ),
        migrations.CreateModel(
            name="GuildTicketSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_id",
                    models.PositiveBigIntegerField(
                        help_text="ID of the channel category where tickets will be created",
                        null=True,
                    ),
                ),
                (
                    "archive_category_id",
                    models.PositiveBigIntegerField(
                        help_text="ID of the channel category where archived tickets will be moved",
                        null=True,
                    ),
                ),
                (
                    "roles",
                    models.JSONField(
                        help_text="List of role IDs that can see tickets", null=True
                    ),
                ),
                (
                    "ticket_count",
                    models.PositiveBigIntegerField(
                        default=1, help_text="Counter for tickets created in the guild"
                    ),
                ),
                (
                    "auto_archive_days",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Number of days after which closed tickets are automatically archived",
                    ),
                ),
                (
                    "allow_user_close",
                    models.BooleanField(
                        default=True,
                        help_text="Whether users can close their own tickets",
                    ),
                ),
                (
                    "allow_user_reopen",
                    models.BooleanField(
                        default=True,
                        help_text="Whether users can reopen their closed tickets",
                    ),
                ),
                (
                    "guild",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_settings",
                        to="demolizzen.guildprofile",
                    ),
                ),
            ],
            options={
                "db_table": "guild_ticket_settings",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GuildTicketTask",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "channel_name",
                    models.CharField(
                        help_text="Name of the channel for the ticket",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("topic", models.TextField(help_text="Topic of the ticket", null=True)),
                (
                    "is_queued",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the task is queued for processing",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the task was created",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the task was completed",
                        null=True,
                    ),
                ),
                (
                    "has_error",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the task encountered an error during processing",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="demolizzen.guildticket",
                    ),
                ),
            ],
            options={
                "db_table": "guild_ticket_tasks",
                "default_permissions": (),
            },
        ),
    ]
