# Generated by Django 5.2.6 on 2025-09-14 18:31

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demolizzen", "0002_guildsettings_guildticket_guildticketsettings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userminingmission",
            name="insurance",
        ),
        migrations.RemoveField(
            model_name="userraidmission",
            name="insurance",
        ),
    ]
