# Generated by Django 5.2.6 on 2025-09-11 10:10

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demolizzen", "0002_guildsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="guildsettings",
            name="help_channel",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="guildsettings",
            name="ticket_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="guildsettings",
            name="guild",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guild_settings",
                to="demolizzen.guildprofile",
            ),
        ),
    ]
