# Generated by Django 5.2.6 on 2025-09-11 15:39

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demolizzen", "0003_guildsettings_help_channel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuildTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_number", models.IntegerField()),
                ("thread_id", models.BigIntegerField()),
                ("user_id", models.BigIntegerField()),
                ("group_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guild_tickets",
                        to="demolizzen.guildprofile",
                    ),
                ),
            ],
            options={
                "db_table": "guild_tickets",
                "default_permissions": (),
                "unique_together": {("guild", "ticket_number")},
            },
        ),
    ]
