# Generated by Django 5.2.6 on 2025-09-14 20:39

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demolizzen", "0003_remove_userminingmission_insurance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guildsettings",
            name="bank_interest",
        ),
        migrations.CreateModel(
            name="GuildBankSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_deposits",
                    models.BooleanField(default=True, help_text="Allow deposits"),
                ),
                (
                    "allow_withdrawals",
                    models.BooleanField(default=True, help_text="Allow withdrawals"),
                ),
                (
                    "interest_rate",
                    models.FloatField(default=0.001, help_text="Daily interest rate"),
                ),
                (
                    "last_interest_update",
                    models.DateTimeField(
                        help_text="Timestamp of the last interest update", null=True
                    ),
                ),
                (
                    "guild",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_settings",
                        to="demolizzen.guildprofile",
                    ),
                ),
            ],
            options={
                "db_table": "guild_bank_settings",
                "default_permissions": (),
            },
        ),
    ]
