# Generated by Django 5.2.6 on 2025-09-15 19:41

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demolizzen", "0004_remove_guildsettings_bank_interest_guildbanksettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guildprofile",
            name="main_channel",
        ),
        migrations.AddField(
            model_name="guildprofile",
            name="main_channel_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
