# Generated by Django 5.2.6 on 2025-09-22 06:50

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demolizzen", "0005_remove_guildprofile_main_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zkillboard",
            name="threshold",
            field=models.PositiveBigIntegerField(),
        ),
    ]
