# Generated by Django 5.2.6 on 2025-09-22 16:48

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demolizzen", "0006_alter_zkillboard_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="guildticket",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
