# Generated by Django 5.2.6 on 2026-04-02 10:31

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demolizzen", "0007_guildticket_is_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveEntityTask",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, null=True)),
                ("entity_id", models.IntegerField()),
                ("category", models.CharField(max_length=64)),
                ("retry_count", models.IntegerField(default=0)),
                ("last_attempt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "eve_entity_tasks",
                "default_permissions": (),
            },
        ),
    ]
