name: Checks

on:
  push:
    paths-ignore:
      - "**.css"
      - "**.js"
      - "**.md"

    branches:
      - '**'

    tags-ignore:
      - '**'

  pull_request:
    paths-ignore:
      - "**.css"
      - "**.js"
      - "**.md"

    branches:
      - '**'

jobs:
  # Run pre-commit Checks
  pre-commit:
    name: Pre Commit Checks
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml' # Read the Python version from the pyproject.toml file

      - name: Run Pre Commit Checks
        uses: pre-commit/action@v3.0.1
